name: Gunluk BES Raporu Otomasyonu

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kutuphaneleri Yukle
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl requests

    - name: Raporu Calistir
      run: python main.py

    - name: E-Posta Kutuma Otomatik Postala
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ://gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USER }}
        password: ${{ secrets.MAIL_PASS }}
        subject: Günlük Otomatik BES Durum Raporu
        to: ${{ secrets.MAIL_USER }}
        from: BES Yapay Zeka Analiz Ekibi
        body: Yapay zeka ekibiniz tarafından hazırlanan günlük genişlik ayarlı, kâr/zarar hesaplamalı Excel BES durum raporunuz ekte yer almaktadır.
        attachments: "*.xlsx"
